name: "Build introductory app"
on: push
jobs:
  build:
    name: "Export introductory app"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - run: npm install -g yarn

      - run: yarn install

      - run: yarn export
