# .github/workflows/git-sync.yml

on:
  push:
    branches:
      - main
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://${{ secrets.SECRET_KEY }}@github.com//RevereLabs/landing.git"
          source_branch: "main"
          destination_repo: "https://${{ secrets.SECRET_KEY }}@github.com/heemankv/RevereLabs.git"
          destination_branch: "master"